"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
import dj_database_url

from corsheaders.defaults import default_headers
from server.redis_runtime import resolve_backend_redis_settings
from server.runtime_services import (
    env_flag,
    get_backend_media_root,
    host_looks_local,
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Keep shell/host environment authoritative and only fill missing values from .env.
load_dotenv(BASE_DIR / ".env", override=False)
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

from django.core.exceptions import ImproperlyConfigured

DEBUG = bool(int(os.getenv("DJANGO_DEBUG", "0"))) # Default to 0 (False) for safety

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

if not SECRET_KEY:
    if DEBUG:
        # Fallback ONLY permitted in local development
        SECRET_KEY = "django-insecure-local-dev-key-do-not-use-in-prod"
    else:
        raise ImproperlyConfigured("DJANGO_SECRET_KEY environment variable is missing. Refusing to start in production.")

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1,backend,nginx").split(",")

# Application definition

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "channels",
    "api",
    "ai_integration",
]

# Django Channels configuration
# Auto uses Redis whenever a Redis target is configured.
_channel_backend = os.getenv("CHANNEL_LAYER_BACKEND", "auto").strip().lower()
_redis_settings = resolve_backend_redis_settings()
if _channel_backend == "inmemory":
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }
else:
    use_redis = _channel_backend == "redis" or _redis_settings.configured or not DEBUG

    if use_redis:
        CHANNEL_LAYERS = {
            "default": {
                "BACKEND": "channels_redis.core.RedisChannelLayer",
                "CONFIG": {
                    "hosts": [_redis_settings.channels_host],
                },
            },
        }
    else:
        CHANNEL_LAYERS = {
            "default": {
                "BACKEND": "channels.layers.InMemoryChannelLayer",
            }
        }

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "api.middleware.ActiveTenantMiddleware",  
    "api.middleware.QueryCountMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "server.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "server.wsgi.application"
ASGI_APPLICATION = "server.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = (os.getenv("DATABASE_URL") or "").strip()
if not DATABASE_URL:
    raise ImproperlyConfigured(
        "DATABASE_URL is required. SQLite fallback has been removed to enforce PostgreSQL as canonical truth."
    )

# Postgres-only mode: use DATABASE_URL in all environments.
DATABASES = {
    "default": dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=600,  # pools connections to reduce reconnect churn
        conn_health_checks=True,
    )
}


# DRF base config 
REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
    ],
     "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",  # or IsAuthenticated if you want to lock everything by default
    ],
}
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# CORS so the React app / Nginx can call the API
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "CORS_ALLOWED_ORIGINS",
        "http://localhost:8085,http://localhost:5000,http://localhost:3000"
    ).split(",")
]
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = list(default_headers) + [
    "x-tenant-id",      # <-- your custom header
    "authorization",    # good to allow this explicitly too
    "content-type",
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "/media/"
MEDIA_ROOT = get_backend_media_root(BASE_DIR)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ── Email (§4 Notifications) ──────────────────────────────────
# Dev: console backend (prints emails to stdout).
# Production: set SENDGRID_API_KEY or SMTP env vars.
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "vigilzone@localhost")
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() in ("1", "true", "yes")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")

# ── OpenCV preview streaming (snapshot + MJPEG) ─────────────
STREAM_PREVIEW_FPS = int(os.getenv("STREAM_PREVIEW_FPS", "3"))
STREAM_PREVIEW_MAX_WIDTH = int(os.getenv("STREAM_PREVIEW_MAX_WIDTH", "960"))
STREAM_PREVIEW_JPEG_QUALITY = int(os.getenv("STREAM_PREVIEW_JPEG_QUALITY", "70"))
STREAM_IDLE_TTL_SECONDS = int(os.getenv("STREAM_IDLE_TTL_SECONDS", "60"))
OPENCV_FFMPEG_CAPTURE_OPTIONS = os.getenv(
    "OPENCV_FFMPEG_CAPTURE_OPTIONS",
    "rtsp_transport;tcp|stimeout;3000000",
)
STREAM_PREVIEW_PREFER_AI_SNAPSHOTS = os.getenv(
    "STREAM_PREVIEW_PREFER_AI_SNAPSHOTS",
    "1",
).strip().lower() in ("1", "true", "yes", "on")
STREAM_PREVIEW_RTSP_FALLBACK_ENABLED = os.getenv(
    "STREAM_PREVIEW_RTSP_FALLBACK_ENABLED",
    "0",
).strip().lower() in ("1", "true", "yes", "on")
STREAM_PREVIEW_AI_SNAPSHOT_TIMEOUT_SECONDS = float(
    os.getenv("STREAM_PREVIEW_AI_SNAPSHOT_TIMEOUT_SECONDS", "2.0")
)

# ── MediaMTX Relay Identity ─────────────────────────────────
# The canonical hostname and port that THIS deployment's MediaMTX
# instance listens on.  Used to detect and prevent self-referential
# RTSP source loops (camera.rtsp_url pointing back at our own relay).
#
# Local dev:  127.0.0.1:8554  (default)
# Docker:     mediamtx:8554
# Cloud/K8s:  relay.production.svc:8554
RELAY_RTSP_HOST = os.getenv("RELAY_RTSP_HOST", "127.0.0.1")
RELAY_RTSP_PORT = int(os.getenv("RELAY_RTSP_PORT", "8554"))

# All hostnames / IPs that resolve to our own MediaMTX instance.
# Automatically includes localhost variants + the configured RELAY_RTSP_HOST.
_relay_aliases = {
    "127.0.0.1", "localhost", "0.0.0.0", "::1",
    RELAY_RTSP_HOST.lower(),
}
# Allow operators to add extra aliases (e.g. LB DNS, internal CNAME)
_extra = os.getenv("RELAY_RTSP_ALIASES", "").strip()
if _extra:
    _relay_aliases.update(a.strip().lower() for a in _extra.split(",") if a.strip())
RELAY_RTSP_ALIASES: frozenset[str] = frozenset(_relay_aliases)
def _validate_runtime_service_urls() -> None:
    """Fail fast when production-like deployments still point at localhost."""
    allow_local = env_flag("ALLOW_LOCALHOST_SERVICE_URLS", default=False)
    strict_raw = os.getenv("STRICT_SERVICE_URL_VALIDATION", "").strip().lower()
    strict_validation = env_flag("STRICT_SERVICE_URL_VALIDATION", default=(not DEBUG and strict_raw not in {"0", "false", "no", "off"}))

    if not strict_validation or allow_local:
        return

    checks: list[tuple[str, str, tuple[str, ...]]] = [
        ("AI_BASE_INTERNAL", os.getenv("AI_BASE_INTERNAL", "").strip(), ("http", "https")),
        ("MEDIAMTX_API_URL", os.getenv("MEDIAMTX_API_URL", "").strip(), ("http", "https")),
        (
            "MEDIAMTX_INTERNAL_RTSP_URL",
            (os.getenv("MEDIAMTX_INTERNAL_RTSP_URL") or os.getenv("MEDIAMTX_RTSP_BASE") or "").strip(),
            ("rtsp", "rtsps"),
        ),
    ]

    problems: list[str] = []
    for env_name, raw_value, schemes in checks:
        if not raw_value:
            problems.append(f"{env_name} is missing")
            continue

        from urllib.parse import urlparse
        parsed = urlparse(raw_value)
        if not parsed.scheme or parsed.scheme.lower() not in schemes:
            problems.append(f"{env_name} has an invalid URL: {raw_value}")
            continue

        if host_looks_local(parsed.hostname or ""):
            problems.append(
                f"{env_name} points to localhost ({raw_value}). "
                "Set the real internal service address or ALLOW_LOCALHOST_SERVICE_URLS=1 for single-host deployments."
            )

    if not _redis_settings.configured:
        problems.append("REDIS_URL or REDIS_HOST is missing")
    elif _redis_settings.url:
        parsed = urlparse(_redis_settings.url)
        if host_looks_local(parsed.hostname or ""):
            problems.append(
                f"REDIS_URL points to localhost ({_redis_settings.connection_display}). "
                "Use the real Redis service address or ALLOW_LOCALHOST_SERVICE_URLS=1 for single-host deployments."
            )
    elif host_looks_local(_redis_settings.host):
        problems.append(
            f"REDIS_HOST points to localhost ({_redis_settings.connection_display}). "
            "Use the real Redis service address or ALLOW_LOCALHOST_SERVICE_URLS=1 for single-host deployments."
        )

    if problems:
        raise ImproperlyConfigured("Service URL validation failed: " + " | ".join(problems))


_validate_runtime_service_urls()



