# Generated by Django 5.2.7 on 2026-05-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_airuntimeregistration_default_unsynced'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='audio_enabled',
            field=models.BooleanField(default=False, help_text='Enable audio anomaly detection (requires camera with microphone)'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='type',
            field=models.CharField(choices=[('robbery', 'Robbery'), ('stranger', 'Stranger'), ('fire', 'Fire'), ('intrusion', 'Intrusion'), ('audio_anomaly', 'Audio Anomaly'), ('weapon', 'Weapon'), ('fall', 'Fall'), ('violence', 'Violence'), ('accident', 'Accident'), ('other', 'Other')], max_length=24),
        ),
    ]
