# Generated by Django 5.2.7 on 2026-05-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_camera_audio_enabled_alter_incident_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='learned_fusion_mode',
            field=models.CharField(choices=[('off', 'Off'), ('shadow', 'Shadow'), ('active', 'Active')], default='off', help_text='Mode for the AI Learned Fusion head', max_length=16),
        ),
        migrations.AddField(
            model_name='camera',
            name='normality_ema_alpha',
            field=models.FloatField(default=0.05, help_text='Smoothing factor for the background noise EMA baseline'),
        ),
        migrations.AddField(
            model_name='camera',
            name='uncertainty_threshold',
            field=models.FloatField(default=0.6, help_text='Threshold above which audio uncertainty prevents synergy/standalone alerts'),
        ),
    ]
